<a href="https://colab.research.google.com/github/GargiMakhe/ABC/blob/main/Gargi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array1 = np.array([10,20,30,40,50,60,70])
print(array1[1:3])
print(array1[1:6:2])
print(array1[-1:-3:-1])
print(array1[::2])

[20 30]
[20 40 60]
[70 60]
[10 30 50 70]


In [ ]:
import numpy as np
array1 = np.array([[15,16,17],[25,26,27],[35,36,37],[45,46,47]])
print(array1[1,])
print(array1[:,1])
print(array1[1:3,1:3])
print(array1[1:3,])
print(array1[:,1:3])
print(array1[1:3,1])
print(array1[1:3,:1])
print(array1[0,1:3])
print(array1[1:3,0:2])
print(array1[2:4,2])




[25 26 27]
[16 26 36 46]
[[26 27]
 [36 37]]
[[25 26 27]
 [35 36 37]]
[[16 17]
 [26 27]
 [36 37]
 [46 47]]
[26 36]
[[25]
 [35]]
[16 17]
[[25 26]
 [35 36]]
[37 47]


In [ ]:
#Matrix multimplmimcation
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])
z= x @ y
print(z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


In [ ]:
s1="SBJAIN COLLEGE 54678"
print(s1.isupper())
count=0
count1=0
for i in s1:
  if i.isupper():
    count+=1
  if i.islower():
    count1+=1
print(count)
print(count1)

True
13
0


In [ ]:
s="welcome to python programming"
print(s.count("p"))

2


In [ ]:
s="welcome to python programming"
print(s.count("p",10))

2


In [ ]:
s="welcome to python language"
print(s.count("e")) #3 times total count
print(s.count("e",5))

3
2


In [ ]:
#index and find
s="welcome to python programming"
print(s.find("p"))#find first index  position of p ie: 11
print(s.index("p"))#also same
print(s.find("p",12))#find p from 12 index to end
print(s.index("p",12))#same like find
print(s.find("p",1,13))#find p from 1 to 12 index
print(s.index("p",1,13))#same like find
#difference in both
print(s.find("k"))  #give -1
print(s.index("k")) #give error value error
#note find function only available with string
# not available in tupple,list,set but index function available
#isdigit(),isalpha(),isspace(),isnumeric(),isalnum()
s="hello to all 12345 "
countdigit=countalpha=countspace=0
countalphanum=0
for i in s:
    if i.isdigit():
        countdigit+=1
    if i.isalpha():
        countalpha+=1
    if i.isspace():
        countspace+=1
    if i.isalnum():
        countalphanum+=1
print("Total digit-",countdigit)
print("Total alphabet-",countalpha)
print("Total space-",countspace)
print("Total alphabet digit-",countalphanum)

11
11
18
18
11
11
-1


ValueError: substring not found

In [ ]:
s="welcome to all python programming "
print(s.split()) #by default split from space and return answer in list
print(s.split("p"))#jaha jaha p waha , ayega
#partition
#print(s.partition())#here must give value for partion nahi tao error
print(s.partition("p"))
#p ke pahele ek part,then  p,then baki part give answer in tupple
#output=>('welcome to all ', 'p', 'ython programming ')
#jony jony wal aexample

['welcome', 'to', 'all', 'python', 'programming']
['welcome to all ', 'ython ', 'rogramming ']
('welcome to all ', 'p', 'ython programming ')


In [ ]:
#strip,rstrip,ltsrip
s=" sbjain"
print(s)# its print as it is
print(s.lstrip())#remove left space
#rstrip
s="sbjain     "
print(s)
print(s.rstrip())#its remove but nor see
#to see rstrip
s="sbjain     "
print(len(s))#its count all
print(len(s.rstrip()))#after remove ight space
#strip remove both side space
"""
"""
#endswith,startwith,join,replace
s="Python welcome to python"
print(s.endswith("n"))#true
print(s.startswith("w"))#true
#join
print(" ".join(s))#join with each word


 sbjain
sbjain
sbjain     
sbjain
11
6
True
False
P y t h o n   w e l c o m e   t o   p y t h o n


In [ ]:
#list demo empty list
my_list1 = [1,2,3,4,5,6,7,8,9]
print(my_list1)
my_list2=list([])
print(my_list2)


[1, 2, 3, 4, 5, 6, 7, 8, 9]
[]


In [ ]:
#list to print
my_list1=[1,"hindi",33,44,"edurekha"]
my_list2=list([454,"yogesh","sanjay",55,66,77])
print(my_list1)
print(my_list2)

[1, 'hindi', 33, 44, 'edurekha']
[454, 'yogesh', 'sanjay', 55, 66, 77]


In [ ]:
#print list using slice
my_list1=[1,"hindi",33,44,"edurekha"]
print(my_list1[:])
print(my_list1[0:3])
print(my_list1[::-1])
print(my_list1[0:5:2])
print(my_list1[1][2])
print(my_list1[-1][1])

[1, 'hindi', 33, 44, 'edurekha']
[1, 'hindi', 33]
['edurekha', 44, 33, 'hindi', 1]
[1, 33, 'edurekha']
n
d


In [ ]:
l1=[11,22,33]
l2=[44,55,66]
print(l1+l2)
print(l1*3)
print(l1*3+l2*3)
print((l1+l2)*3)

[11, 22, 33, 44, 55, 66]
[11, 22, 33, 11, 22, 33, 11, 22, 33]
[11, 22, 33, 11, 22, 33, 11, 22, 33, 44, 55, 66, 44, 55, 66, 44, 55, 66]
[11, 22, 33, 44, 55, 66, 11, 22, 33, 44, 55, 66, 11, 22, 33, 44, 55, 66]


In [ ]:
# shows append,insert,extent function of list
my_list1=[1,"hindi",33,44,"edurekha"]
my_list1.append([555,22] )    #USE OF APPEND FUNCTION
print(my_list1)
print(len(my_list1))
my_list1.extend([444,666])    #USE OF EXTEND FUN
print(my_list1)
print(len(my_list1))
my_list1.insert(1,"sanjay")    #USE OF INSERT FUNCTION
print(my_list1)
print(len(my_list1))
print(my_list1 + [ "katre"])   #add content to given list but original list not effect
print(my_list1)
print(my_list1 *2)   #list is multiply by 2 shows list 2 times
print(my_list1)

[1, 'hindi', 33, 44, 'edurekha', [555, 22]]
6
[1, 'hindi', 33, 44, 'edurekha', [555, 22], 444, 666]
8
[1, 'sanjay', 'hindi', 33, 44, 'edurekha', [555, 22], 444, 666]
9
[1, 'sanjay', 'hindi', 33, 44, 'edurekha', [555, 22], 444, 666, 'katre']
[1, 'sanjay', 'hindi', 33, 44, 'edurekha', [555, 22], 444, 666]
[1, 'sanjay', 'hindi', 33, 44, 'edurekha', [555, 22], 444, 666, 1, 'sanjay', 'hindi', 33, 44, 'edurekha', [555, 22], 444, 666]
[1, 'sanjay', 'hindi', 33, 44, 'edurekha', [555, 22], 444, 666]


In [ ]:
my_list1=[1,"hindi",33,44,"edurekha"]
print(len(my_list1))
my_list1.insert(1,"sanjay")

5


In [ ]:
l=[11,22,33]
print(l.insert(1,99))

None


In [ ]:
l=[1,2,3,4,5,6,7]
l.reverse()
print(l)

[7, 6, 5, 4, 3, 2, 1]


In [ ]:
# index ,count in list
my_list1=[1, 'sanjay', 'hindi', 33, 44, 'edurekha']
print(my_list1.index("edurekha"))  #find index no. of element
print(my_list1.count("edurekha"))   #find how many times particular element in a given list
new = [11, 45, 22, 1, 3]
print(sorted(new))  # sorted new list element and print but original not change
print(new)             # ORIGINAL PRINT AS IT Is
new.sort(reverse=True)  #short original list in decending order if rev=true else accending order
print(new)
new.reverse()
print(new)

5
1
[1, 3, 11, 22, 45]
[11, 45, 22, 1, 3]
[45, 22, 11, 3, 1]
[1, 3, 11, 22, 45]


In [ ]:
L=['a','e','i','o','u']
T=tuple(L)
T

('a', 'e', 'i', 'o', 'u')

In [ ]:
t=()
print(type(t))
t=tuple()
print(t)

<class 'tuple'>
()


In [ ]:
t=1,2
print(type(t))
t=tuple()
print(t)

<class 'tuple'>
()


In [ ]:
t=(1,2,3,4)
print(t)
t=(1.2,1.2,1.4,"a")
print(t)

(1, 2, 3, 4)
(1.2, 1.2, 1.4, 'a')


In [ ]:
#create different tuple
t=(1,2,3,4)
print(t)
t=(1.2,1.2,1.4,"a")
print(t)
#nested tuple
t=(1,2,3,(44,55))
print("NESTED TUPPLE=>",t)

(1, 2, 3, 4)
(1.2, 1.2, 1.4, 'a')
NESTED TUPPLE=> (1, 2, 3, (44, 55))


In [ ]:
#take input from user
t1=tuple(input("Enter Element:"))
print(t1)

Enter Element:1234
('1', '2', '3', '4')


In [ ]:
#convert into tupple
l=[1,2,3]
print(tuple(l))
s="python"
print(tuple(s))
#conver dic to tuple
d={1:"a",2:"b",3:"c"}
print(tuple(d))  #by default key
print(tuple(d.values())) #here value take not keys

(1, 2, 3)
('p', 'y', 't', 'h', 'o', 'n')
(1, 2, 3)
('a', 'b', 'c')


In [ ]:
#packed and unpacked
t=1,2   #packed
print(t)
x,y=(1,2)  #unpacked
print(x,y)

(1, 2)
1 2


In [ ]:
#concatenete,replicate,membership
t=(11,22,33)
print(t)
print(id(t))
t=t*3
print(t)
print(id(t))

(11, 22, 33)
133087987166656
(11, 22, 33, 11, 22, 33, 11, 22, 33)
133087986915632


In [ ]:
tp1=(1,3,5)
tp2=(6,7,8)
tp1+tp2(1,3,5,6,7,8)
tp3=tp1+tp2
tp3
(1,3,5,6,7,8)

TypeError: 'tuple' object is not callable

In [ ]:
#slicing
t=(99,88,77,66,55,44,33,22)
print(t[0:5])  #0 to 3
print(t[::-1])  #reverse
print(t[-1:-5:-1])  #22,33,44,55  start :end-1:step

(99, 88, 77, 66, 55)
(22, 33, 44, 55, 66, 77, 88, 99)
(22, 33, 44, 55)


In [ ]:
tp1=(10,12,14,20,22,24,30,32,34)
seq=tp1[3:-3]
seq
seq=tp1[1:-3]
seq

(12, 14, 20, 22, 24)

In [ ]:
#tuple function
t=(11,22,33,44,44,55,44)
print(len(t))  #4
print(max(t))  #55
print(min(t))  #11
print(t.index(44))
print(t.count(44))
print(sum(t))
print(sorted(t))
print(sorted(t,reverse=True))

7
55
11
3
3
253
[11, 22, 33, 44, 44, 44, 55]
[55, 44, 44, 44, 33, 22, 11]


In [ ]:
#Create a tuple with three elements: 10, “hello”, and 3.14.
t=(10,"hello","3.14")
print(t)

(10, 'hello', '3.14')


In [ ]:
#create dictionary
dic={ }  #empty dictionary
print(dic)
print(type(dic))
d=dict()
print(d)
print(type(d))
d={1:"x",2:"y",3:"z"}
print(d)
print(d.keys())
print(d.values())
print(d.items())

{}
<class 'dict'>
{}
<class 'dict'>
{1: 'x', 2: 'y', 3: 'z'}
dict_keys([1, 2, 3])
dict_values(['x', 'y', 'z'])
dict_items([(1, 'x'), (2, 'y'), (3, 'z')])


In [ ]:
#four ways to create dictionary
d1= {"a":"apple","b":"orange","c":"mango"}
d2=dict(a="apple",b="orange",c="mango")
d3=dict([("a","apple"),("b","orange"),("c","mango")])
d4=dict({"a":"apple","b":"orange","c":"mango"})
print(d1==d2==d3==d4)

True


In [ ]:
d={1:"xx",2:"yy",3:"uu"}
print(d[1])#1 indicate key


xx


In [ ]:
#create empty dictionary and add item
d1=dict()
d1[1]="one"
d1[2]="two"
d1[3]="three"
d1[4]="four"
print(d1)


{1: 'one', 2: 'two', 3: 'three', 4: 'four'}


In [ ]:
#dictionary traversal
d={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
for i in d:
    print(i,end=" ")#keys print
print()
for i in d:
    print(d[i],end=" ")#value of key print
print()
for i in d.values():
    print(i,end=" ")
print()
for i in d:
    print("key=>",i,"value=>",d[i])#value of key print

1 2 3 4 
one two three four 
one two three four 
key=> 1 value=> one
key=> 2 value=> two
key=> 3 value=> three
key=> 4 value=> four


In [ ]:
d={1: 'one', 2: 'two', 3: 'three', 4: 'four',}
d[6]="six"
#d[1]="xxxxx"
print(d)

{1: 'one', 2: 'two', 3: 'three', 4: 'four', 6: 'six'}


In [ ]:
#copy dictionary
d1={1: 'one', 2: 'two' , 3: 'three', 4: 'four'}
d2=d1#both refer to same address so one change reflect on other also
print(id(d1))
print(id(d2))

133727285094976
133727285094976


In [ ]:
#len()
d={ 2: 'two',1: 'one',4: 'four',3: 'three'}
print(len(d))

4


In [ ]:
#update
d1={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
d2={5:"five"}
d1.update(d2)
print(d1)
print(d2)


{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}
{5: 'five'}


In [ ]:
#pop
set1={2,3,4,5,6,"a"}
item=set1.pop()
print(item)
print(set1)
"""
s1={1,2,3}
s2={4,5,6}
print(s1.union(s2))
print(s1.intersection(s2))

SyntaxError: incomplete input (ipython-input-2777965528.py, line 6)

In [ ]:
#sorted
d={ 2: 'two',1: 'one',4: 'four',3: 'three'}
print(sorted(d.items()))#all keys sorted and store in list
d={ 2: 'two',1: 'one',4: 'four',3: 'three'}
print(sorted(d,reverse=True))


[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]
[4, 3, 2, 1]


In [ ]:
def sum():
    a=int(input("Enter value of a:"))
    b = int(input("Enter value of b:"))
    print(a+b)

sum()     #funtion call
sum()

Enter value of a:13
Enter value of b:13
26
Enter value of a:13
Enter value of b:13
26


In [ ]:
#function call without argument without return
def evenodd():
    num=int(input("Enter a number:"))
    if num%2==0:
        print(num,"even number")
    else:
        print(num, "odd number")

evenodd()

Enter a number:20
20 even number


In [ ]:
#function call with argument pass  without return
def evenodd(n):
    if  n% 2 == 0:
        print(n, "even number")
    else:
        print(n, "odd number")

num = int(input("Enter a number:"))
evenodd(num)  #pass argument


Enter a number:66
66 even number


In [ ]:
#function call with argument pass with return
def add(a,b):

    sum=a+b
    return  sum

n1=int(input("Enter  number:"))
n2 = int(input("Enter  number:"))
result=add(n1,n2)  #pass  argument
print("sum of two number:",result)

Enter  number:10
Enter  number:10
sum of two number: 20


In [ ]:
#wap to find cube of given number using all four methode.
#Wap to find factorial of number using all four methode.


In [ ]:
#multiple value return
def example():
    return 11,22,33
print(example())

def example():
    return 11,22,33,44

t=example()
print(t)
a,b,c,d=example() #here also packed so unpacked
print(a,b,c,d,sep=" ")


(11, 22, 33)
(11, 22, 33, 44)
11 22 33 44


In [ ]:
def Student(name,marks=33):
  print(name)
  print(marks)

Student('Lovejeet',50)

Lovejeet
50


In [ ]:
def Student(name,marks=33):
  print(name)
  print(marks)

Student('Lovejeet')

Lovejeet
33


In [ ]:
def ADD(Sci,Maths,Eng=90,Hindi=9):
  print(Sci+Maths+Eng+Hindi)
ADD(Maths=99,Sci=90)

288


In [ ]:
#example
def fun1():
  x=10  #local
  print(x)
def fun2():
  x=290
  print(x)
x=100    #global
fun1()
fun2()

10
290
